### PR TITLE
Only publish interactive if in desired state

### PR DESCRIPTION
**Pull request by mryan321**
### What

Do not allow publish to complete if interactive not in desired state (`ImportSuccess`) - i.e. when the upload process has completed and successful.

@nimitsarup - i think the publish action would be better for a PATCH request 🤔  esp from zebedee otherwise you risk a bad update after doing a rountrip to grab interactive then pass the correct payload. wha ya reckon? 😊 

### How to review

Sanity check

### Who can review

Anyone

### CODE REVIEW

**Review by nimitsarup — DISMISSED** [review]

**Comment by nimitsarup** [comment]
hi @mryan321  i approved before reading your message.
Putting this check in the update is also needed (as theoretically the publish can be set in that request - we can obvioously choose not to action on that in this request - OR pass back an error message which we are doing now after your change).
Yes my vote is for PATCH.. much cleaner

**Comment by mryan321** [comment]
> hi @mryan321 i approved before reading your message. Putting this check in the update is also needed (as theoretically the publish can be set in that request - we can obvioously choose not to action on that in this request - OR pass back an error message which we are doing now after your change). Yes my vote is for PATCH.. much cleaner

Cool - we can look at refactoring to a PATCH maybe later - but this change is in the ` UpdateInteractiveHandler` - I didnt add to upload one because I dont think a valid journey - upload new interactive and publish? I dont think this is possible yeah? 🤔

**Comment by nimitsarup** [comment]
> > hi @mryan321 i approved before reading your message. Putting this check in the update is also needed (as theoretically the publish can be set in that request - we can obvioously choose not to action on that in this request - OR pass back an error message which we are doing now after your change). Yes my vote is for PATCH.. much cleaner
> 
> Cool - we can look at refactoring to a PATCH maybe later - but this change is in the ` UpdateInteractiveHandler` - I didnt add to upload one because I dont think a valid journey - upload new interactive and publish? I dont think this is possible yeah? thinking

Oh yes indeed . i meant the update

**Comment by mryan321** [comment]
> > hi @mryan321 i approved before reading your message. Putting this check in the update is also needed (as theoretically the publish can be set in that request - we can obvioously choose not to action on that in this request - OR pass back an error message which we are doing now after your change). Yes my vote is for PATCH.. much cleaner
> 
> Cool - we can look at refactoring to a PATCH maybe later - but this change is in the ` UpdateInteractiveHandler` - I didnt add to upload one because I dont think a valid journey - upload new interactive and publish? I dont think this is possible yeah? 🤔

yep - it is invalid because this is an async flow 😊  it will never be in a valid state to publish on initial upload - we need to wait

**Review by nimitsarup — APPROVED** [review]

**Pull request merged**
